[package]
name = "bfc-win-placeholder"
version = "1.0.0-placeholder"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
