name: Build executables
on: [workflow_dispatch]
jobs:
    build_64bit_GNU:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Install gcc-mingw-w64
              run: sudo apt-get install gcc-mingw-w64 -y
            - name: Install rust target x86_64-pc-windows-gnu
              run: rustup target add x86_64-pc-windows-gnu
            - name: Install cargo make
              run: cargo install cargo-make
            - name: Set permissions for script
              run: sudo chmod +x scripts/build-x86_64-pc-windows-gnu.sh
            - name: Build with cargo-make
              run: cargo make
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: bfc-win-x86_64-pc-windows-gnu
                path: output/bfc-win-x86_64-pc-windows-gnu.exe