name: Build 32bit using GNU Linux
on: [workflow_dispatch]
jobs:
  build_32bit_GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install gcc-mingw-w64
        run: sudo apt-get install gcc-mingw-w64 -y
      - name: Cache 32bit linux cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-32bit-${{ hashFiles('**/Cargo.lock') }}
      - name: Install rust target i686-pc-windows-gnu
        run: rustup target add i686-pc-windows-gnu
      - name: Install cargo make
        run: if [ ! -f "~/.cargo/bin/cargo-make" ]; then cargo install cargo-make; fi
      - name: Set permissions for script
        run: sudo chmod +x scripts/build-i686-pc-windows-gnu.sh
      - name: Build with cargo-make
        run: cargo make -e CARGO_MAKE_RUST_TARGET_TRIPLE=i686-pc-windows-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bfc-win-i686-pc-windows-gnu
          path: output/bfc-win-i686-pc-windows-gnu.exe
