name: Build 64bit using MSVC Windows
on: [workflow_dispatch]
jobs:
    build_64bit_MSVC:
      runs-on: [self-hosted,windows]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Install rust target x86_64-pc-windows-msvc
          run: rustup target add x86_64-pc-windows-msvc
        - name: Install cargo make
          run: cargo install cargo-make
        - name: Build with cargo-make
          run: cargo make -e CARGO_MAKE_RUST_TARGET_TRIPLE=x86_64-pc-windows-msvc
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: bfc-win-x86_64-pc-windows-msvc
            path: output/bfc-win-x86_64-pc-windows-msvc.exe
