name: Build 32bit using MSVC Windows
on: [workflow_dispatch]
jobs:
    build_32bit_MSVC:
      runs-on: windows-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        - name: Cache 64bit linux cargo
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-32bit-${{ hashFiles('**/Cargo.lock') }}
        - name: Install rust target i686-pc-windows-msvc
          run: rustup target add i686-pc-windows-msvc
        - name: Install cargo make
          run: if (!(Test-Path -Path "~/.cargo/bin/cargo-make.exe")) { cargo install cargo-make }
        - name: Build with cargo-make
          run: cargo make -e CARGO_MAKE_RUST_TARGET_TRIPLE=i686-pc-windows-msvc
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: bfc-win-i686-pc-windows-msvc
            path: output/bfc-win-i686-pc-windows-msvc.exe
