name: Build 64bit using GNU Linux
on: [workflow_dispatch]
jobs:
  build_64bit_GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Install latest nightly for x86_64-pc-windows-gnu
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          override: true
      - name: Install cargo-make
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          version: latest
      - name: Set permissions for script
        run: sudo chmod +x scripts/build-x86_64-pc-windows-gnu.sh
      - name: Use Rust/Cargo Cache
        uses: Swatinem/rust-cache@v2.2.1
      - name: Build with cargo-make
        run: cargo make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bfc-win-x86_64-pc-windows-gnu
          path: output/bfc-win-x86_64-pc-windows-gnu.exe
